interface UsuarioForm {
    nome :           string,
    cpf:             string,
    cnpj:            string,
    rg:              string,
    CRM:             string,
    CRP:             string, 
    email:           string,
    endereco:        string,
    cidade:          string,
    bairro:          string,
    uf:              string,
    cep:             string,
    complemento:     string,
    data_nascimento: string,
    telefone:        string,
    celular:         string,
    profissao:       string,
    caminho_foto:    string,
    status:          string,
    observacao:      string,
    login:           string,
    senha:           string,
    tipo:            string,
    permissoes: []
}